# nav2_params.yaml

# 地图服务（map_server）无需改动，直接加载静态 map.yaml
map_server:
  ros__parameters:
    yaml_filename: "MAP_FILE_PLACEHOLDER"
    use_sim_time: false

# 全局代价地图，仅用静态层
global_costmap:
  ros__parameters:
    plugin_names: ["static_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    use_sim_time: false

# 局部代价地图，仅用静态层，不订阅 /scan
local_costmap:
  ros__parameters:
    plugin_names: ["static_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    use_sim_time: false

# Planner Server：只加载 GridBased（Navfn A*）
planner_server:
  ros__parameters:
    planner_plugin_ids: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
    use_sim_time: false

# Controller Server：只加载 DWB 控制器
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_theta: -1.0
      max_vel_theta: 1.0
      acc_lim_x: 0.5
      acc_lim_theta: 3.2

      critics: ["GoalAlign", "PathAlign", "GoalDist"]  # 仅保留路径规划相关 Critic

      GoalAlign:
        plugin: "dwb_critics::GoalAlignCritic"
        scale: 1.0

      PathAlign:
        plugin: "dwb_critics::PathAlignCritic"
        scale: 1.0

      GoalDist:
        plugin: "dwb_critics::GoalDistCritic"
        scale: 1.0

    use_sim_time: false

# 行为树导航器：使用默认 NavigateToPose BT
bt_navigator:
  ros__parameters:
    # 用于单点导航的行为树
    # default_nav_to_pose_bt_xml: "navigate_w_replanning_time.xml"
    # default_nav_through_poses_bt_xml: "navigate_w_replanning_time.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_clear_costmap_service_bt_node    # 新增恢复行为插件
      - nav2_spin_action_bt_node              # 新增旋转恢复插件
      - nav2_back_up_action_bt_node           # 新增后退恢复插件
    default_nav_to_pose_bt_xml: "$(find-pkg-share control_planner)/param/simple_nav_to_pose.xml"

    use_sim_time: false

behavior_server:
  ros__parameters:
    plugin_lib_names:
      - spin
      - wait
      - backup
      - drive_on_heading
    spin:
      plugin: "nav2_behaviors/Spin"
    wait:
      plugin: "nav2_behaviors/Wait"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    use_sim_time: false


# 生命周期管理：启动以下节点
lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - map_server
      - planner_server
      - controller_server
      - bt_navigator
      - behavior_server
